cli: rework into a multicall binary
coreos/bootupd pull request #32
Opened 2020-09-23 10:28 UTC by lucab

This reworks the CLI options parser to branch the inner logic
to accommodate two entrypoints, `bootupd` and `bootupctl`, into
a single multicall binary.

2020-09-23 10:48 UTC, lucab commented
CI complains about:
```
Executing `postprocess` inline script '0'
+ /usr/bin/bootupctl backend generate-update-metadata /
error: Found argument 'backend' which wasn't expected, or isn't valid in this context

USAGE:
    bootupctl <SUBCOMMAND>
```

Am I right assuming that we'd like this to be `bootupd backend` instead? Perhaps I should leave an hidden one on `bootupctl` for the time being in order to ratchet changes?

2020-09-23 13:10 UTC, cgwalters requested changes
> Am I right assuming that we'd like this to be bootupd backend instead? 

I think we want it to be `/usr/libexec/bootupd generate-update-metadata`.  Though this is debatable for sure.  I'd most like for the main binary in `/usr/bin` to be the "end user facing" thing and keep the daemon and backend bits separate.

> Perhaps I should leave an hidden one on bootupctl for the time being in order to ratchet changes?

Yeah I think we should ratchet.  Though I wouldn't have a problem force-pushing an update to https://github.com/coreos/fedora-coreos-config/pull/595 after force-landing a PR.

2020-09-23 13:16 UTC, cgwalters commented on src/cli/mod.rs
> +    about = "Bootload updater, backend and daemon logic."
```suggestion
    about = "Backend commands"
``` ?

2020-09-24 14:47 UTC, cgwalters commented on tests/kola/test-bootupd
> +bootupd backend generate-update-metadata /
This will also need to be `/usr/libexec/bootupd` since `/usr/libexec` is intentionally not in `$PATH`.

2020-09-24 15:50 UTC, cgwalters commented
Looks like this needs a rebase.

2020-09-25 07:44 UTC, lucab commented
/uncc @ashcrow @bgilbert

2020-09-25 08:46 UTC, lucab commented
Rebased, CI is green.

2020-09-25 12:44 UTC, cgwalters approved these changes
/lgtm

2020-09-25 12:58 UTC, merged